@base_url=http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzE4NmFlZjJkZTQzNzJhMmRkM2I1MzkiLCJlbWFpbCI6Imd2QGdtYWlsLmNvbSIsInJvbGUiOiJURUFDSEVSIiwiaWF0IjoxNzI5NjUzNTIxLCJleHAiOjE3Mjk2NTcxMjF9.9WTkMZNjezD_WmSaqlpo1vwd0ml7TzLT09os7gPYXWo

### Login user (anonymous)
POST {{base_url}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "identifier": "gv@gmail.com",
    "password": "gv"
}

# {
#     "identifier": "vanmanh0888@gmail.com",
#     "password": "vanmanh"
# }

### Register user (anonymous)
POST {{base_url}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "Giao vien",
    "email": "gv@gmail.com",
    "password": "gv",
    "role": "teacher"
}

# {
#     "studentId": "21522328",
#     "name": "Ngo Van Manh",
#     "email": "vanmanh0888@gmail.com",
#     "password": "vanmanh",
#     "role": "Student"
# }

### Test
GET {{base_url}}/test HTTP/1.1
Authorization: Bearer {{token}}

### Create Exam (teacher)
POST {{base_url}}/exam HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "exam test",
    "authorIds": [
        "671783a0d61b16b970cac171"
    ],
    "questions": [
        {
            "question": "Tui ten gi",
            "point": 1,
            "options": [
                {
                    "option": "Manh",
                    "isCorrect": true
                },
                {
                    "option": "Loz",
                    "isCorrect": false
                }
            ]
        }
    ]
}

### Delete Exam by its id (teacher and author of exam)
DELETE {{base_url}}/exam/67186f01c51fae3fae41e973 HTTP/1.1
Authorization: Bearer {{token}}

### Get Exam by its code (allow anonymous)
GET {{base_url}}/exam/bonizc HTTP/1.1

### Join exam by code (teacher, student)
GET {{base_url}}/exam/123123/join HTTP/1.1
Authorization: Bearer {{token}}

### Save user selections (teacher, student)
PATCH {{base_url}}/exam/123123/save-selected-options HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "questionId": "6717947cfc7a59a5dca22466",
    "selectedOptions": [
        "6717947cfc7a59a5dca22467"
    ]
}

### Get Exam Record by its code (teacher, student)
### Teacher get list student who joined in exam
### Student get yourselft
GET {{base_url}}/exam/123123/record HTTP/1.1
Authorization: Bearer {{token}}
